[project]
name = "pucp-metrix"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyphen>=0.17.2",
    "spacy>=3.8.5",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
